target "Trippple" do
  pod 'HotlineSDK' => '1.0.13'
  pod 'Mixpanel'
  pod 'NewRelicAgent'
  pod 'Fabric'
  pod 'Crashlytics'
  # pod 'FBSnapshotTestCase'
end

#
# target "Tripppletest" do
#   pod 'HotlineSDK'
#   pod 'Mixpanel'
#   pod 'NewRelicAgent'
#   pod 'FBSnapshotTestCase'
# end
