target "Trippple" do
  pod 'HotlineSDK' => '1.0.13'
  pod 'Mixpanel', :git => 'https://github.com/mixpanel/mixpanel-iphone.git'
  pod 'NewRelicAgent'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'UXCam'
end
