target "Trippple" do
  pod 'HotlineSDK'
  pod 'Mixpanel'
  pod 'NewRelicAgent'
  # pod 'FBSnapshotTestCase'
end

#
# target "Tripppletest" do
#   pod 'HotlineSDK'
#   pod 'Mixpanel'
#   pod 'NewRelicAgent'
#   pod 'FBSnapshotTestCase'
# end
