//
//  UIColor+TRColors.h
//
//  Generated by Zeplin on 11/18/15.
//  Copyright (c) 2015 TRIPPPLE. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (TRColors)

+ (UIColor *)tr_mediumPurpleColor;
+ (UIColor *)tr_mediumPurple20PcColor;
+ (UIColor *)tr_rollingStoneColor;
+ (UIColor *)tr_whiteColor;
+ (UIColor *)tr_shuttleGrayColor;
+ (UIColor *)tr_outerSpaceColor;
+ (UIColor *)tr_mediumPurple20Pc1Color;
+ (UIColor *)tr_white20PcColor;
+ (UIColor *)tr_sushiColor;
+ (UIColor *)tr_atlantisColor;
+ (UIColor *)tr_mandyColor;
+ (UIColor *)tr_whiteishColor;
+ (UIColor *)tr_darkSkyBlueColor;
+ (UIColor *)tr_darkSkyBlue20Color;
+ (UIColor *)tr_duskColor;
+ (UIColor *)tr_warmGreyColor;
+ (UIColor *)tr_dark0Color;
+ (UIColor *)tr_steelGrey20Color;
+ (UIColor *)tr_darkishPink20Color;
+ (UIColor *)tr_blackColor;
+ (UIColor *)tr_lavenderColor;
+ (UIColor *)tr_black20Color;
+ (UIColor *)tr_black25Color;
+ (UIColor *)tr_darkColor;
+ (UIColor *)tr_black10Color;
+ (UIColor *)tr_ceriseColor;
+ (UIColor *)tr_royalColor;
+ (UIColor *)tr_sapphire50Color;
+ (UIColor *)tr_purpleColor;
+ (UIColor *)tr_dandelionColor;
+ (UIColor *)tr_purpley40Color;

@end
