//
//  UIColor+TRColors.m
//
//  Generated by Zeplin on 11/18/15.
//  Copyright (c) 2015 TRIPPPLE. All rights reserved.
//

#import "UIColor+TRColors.h"

@implementation UIColor (TRColors)

+ (UIColor *)tr_mediumPurpleColor {
    return [UIColor colorWithRed:132.0f / 255.0f green:89.0f / 255.0f blue:218.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_mediumPurple20PcColor {
    return [UIColor colorWithRed:131.0f / 255.0f green:89.0f / 255.0f blue:218.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_rollingStoneColor {
    return [UIColor colorWithRed:120.0f / 255.0f green:129.0f / 255.0f blue:135.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_whiteColor {
    return [UIColor colorWithWhite:255.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_shuttleGrayColor {
    return [UIColor colorWithRed:86.0f / 255.0f green:96.0f / 255.0f blue:103.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_outerSpaceColor {
    return [UIColor colorWithRed:44.0f / 255.0f green:57.0f / 255.0f blue:65.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_mediumPurple20Pc1Color {
    return [UIColor colorWithRed:132.0f / 255.0f green:89.0f / 255.0f blue:218.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_white20PcColor {
    return [UIColor colorWithWhite:255.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_sushiColor {
    return [UIColor colorWithRed:66.0f / 255.0f green:181.0f / 255.0f blue:125.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_atlantisColor {
    return [UIColor colorWithRed:129.0f / 255.0f green:209.0f / 255.0f blue:53.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_mandyColor {
    return [UIColor colorWithRed:232.0f / 255.0f green:74.0f / 255.0f blue:107.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_whiteishColor {
    return [UIColor colorWithWhite:216.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_darkSkyBlueColor {
    return [UIColor colorWithRed:65.0f / 255.0f green:182.0f / 255.0f blue:225.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_darkSkyBlue20Color {
    return [UIColor colorWithRed:65.0f / 255.0f green:182.0f / 255.0f blue:225.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_duskColor {
    return [UIColor colorWithRed:61.0f / 255.0f green:63.0f / 255.0f blue:96.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_warmGreyColor {
    return [UIColor colorWithWhite:151.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_dark0Color {
    return [UIColor colorWithRed:44.0f / 255.0f green:57.0f / 255.0f blue:65.0f / 255.0f alpha:0.0f];
}

+ (UIColor *)tr_steelGrey20Color {
    return [UIColor colorWithRed:120.0f / 255.0f green:129.0f / 255.0f blue:135.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_darkishPink20Color {
    return [UIColor colorWithRed:232.0f / 255.0f green:73.0f / 255.0f blue:107.0f / 255.0f alpha:0.2f];
}

+ (UIColor *)tr_blackColor {
    return [UIColor colorWithWhite:0.0f alpha:1.0f];
}

+ (UIColor *)tr_lavenderColor {
    return [UIColor colorWithRed:179.0f / 255.0f green:152.0f / 255.0f blue:232.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_black20Color {
    return [UIColor colorWithWhite:0.0f alpha:0.2f];
}

+ (UIColor *)tr_black25Color {
    return [UIColor colorWithWhite:0.0f alpha:0.25f];
}

+ (UIColor *)tr_darkColor {
    return [UIColor colorWithRed:36.0f / 255.0f green:49.0f / 255.0f blue:56.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_black10Color {
    return [UIColor colorWithWhite:0.0f alpha:0.1f];
}

+ (UIColor *)tr_ceriseColor {
    return [UIColor colorWithRed:217.0f / 255.0f green:25.0f / 255.0f blue:132.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_royalColor {
    return [UIColor colorWithRed:9.0f / 255.0f green:36.0f / 255.0f blue:153.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)tr_sapphire50Color {
    return [UIColor colorWithRed:71.0f / 255.0f green:36.0f / 255.0f blue:143.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)tr_purpleColor {
    return [UIColor colorWithRed:72.0f / 255.0f green:36.0f / 255.0f blue:144.0f / 255.0f alpha:1.0f];
}


+ (UIColor *)tr_dandelionColor {
    return [UIColor colorWithRed:255.0f / 255.0f green:233.0f / 255.0f blue:0.0f alpha:1.0f];
}

+ (UIColor *)tr_purpley40Color {
    return [UIColor colorWithRed:132.0f / 255.0f green:89.0f / 255.0f blue:218.0f / 255.0f alpha:0.4f];
}

@end
