const Donnie = {
  userInfo:{
    "id": 28826,
    "active": true,
    "status": "onboarded",
    "email": null,
    "firstname": "DONNIE",
    "lastname": null,
    "phone": "3055282534",
    "gender": "m",
    "bday_month": 5,
    "bday_year": 1973,
    "relationship_status": "single",
    "looking_for_mm": true,
    "looking_for_ff": true,
    "looking_for_mf": true,
    "looking_for_m": true,
    "looking_for_f": true,
    "match_distance": null,
    "match_age_min": 18,
    "match_age_max": 34,
    "privacy": "public",
    "partner_id": null,
    "facebook_user_id": 10102587667086398,
    "bio": "WHAT IS SUPPOSED TO THERE being some of these keywords relating to this email in error or are not the best way is a very long as the registered trademarks R the first time the new",
    "height": "6.0",
    "body_type": "2",
    "couple_id": null,
    "latitude": 25.7725,
    "longitude": -80.2011,
    "is_image_flagged": false,
    "timezone": "EDT",
    "eye_color": "0",
    "hair_color": "2",
    "ethnicity": "White",
    "smoke": "2",
    "drink": "2",
    "bust_size": null,
    "birthday": "1973-05-25",
    "admin_comment": null,
    "is_active_user": true,
    "image_url": "https://trippple-user.s3.amazonaws.com/uploads/28826/ee8fba63-58d4-4fba-9ba0-f5a4bc2e19f3.jpg",
    "thumb_url": "https://trippple-user.s3.amazonaws.com/uploads/users/28826/ddffc733-88b3-4feb-b050-d9bbce8a1205-a.jpg"
  }
}

export default Donnie
