# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

fastlane_version "1.83.0"

default_platform :ios

platform :ios do
  before_all do
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "Trippple") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end



  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    ensure_git_status_clean
    ensure_git_branch(branch: 'master')
    push_to_git_remote
    cert
    sigh
    changelog = prompt(text: "Enter the change log: ", multi_line_end_keyword: "END")
    version = increment_version_number(bump_type: "patch")
    gym(scheme: "Trippple") # Build your app - more options available
    deliver(force: true)
  end

 lane :debug do
    cert
    sigh
    changelog = prompt(text: "Enter the change log: ", multi_line_end_keyword: "END")
    gym(scheme: "TripppleDebug") # Build your app - more options available
    crashlytics(
      notes: "Automatic iOS Debug Build"
    )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    puts exception.inspect
    slack(
      message: exception.message,
      success: false
    )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
