keystore(
  name = 'debug',
  store = 'debug.keystore',
  properties = 'debug.keystore.properties',
  visibility = [
    'PUBLIC',
  ],
)
keystore(
  name = 'release',
  store = 'release.keystore',
  properties = 'release.keystore.properties',
  visibility = [
    'PUBLIC',
  ],
)
